# Generated by Django 5.2.8 on 2025-11-12 05:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='markers/')),
                ('video', models.FileField(upload_to='videos/')),
                ('mind_file', models.FileField(blank=True, null=True, upload_to='minds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
