# Generated by Django 5.2.8 on 2025-11-13 10:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='mind_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_mind_filename),
        ),
    ]
